services:
  sysmetrics:
    image: jonfairbanks/sysmetrics
    restart: always
    environment:
      - DEVICE=MyDevice
      - INFLUX_TOKEN=abcdef123==
      - INFLUX_ORG=MyInfluxOrg
      - INFLUX_BUCKET=MyInfluxBucket
